#!/bin/bash -x

mpg123 -q /opt/bt-speaker/service-login.mp3

# disconnect wifi to prevent dropouts - TODO: check what permissions bt-speaker might need for this (netdev group?)
# ifconfig wlan0 down &